stages:
  - test
  - scan
  - build
  - deploy

variables:
  IMAGE_NAME: gitlab.home:5050/tmd526/flask-api
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

unit-tests:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - pytest test/

semgrep:
  stage: scan
  image: 
    name: semgrep/semgrep
    entrypoint: [""]
  script:
    - semgrep scan --config auto .

gitleaks:
  stage: scan
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script:
    - gitleaks detect --source . -v

trivy:
  stage: scan
  image: 
    name: aquasec/trivy:0.61.0
    entrypoint: [""]
  script:
    - trivy fs --exit-code 1 --severity HIGH,CRITICAL .

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
