apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: gitlab.home:5050/tmd526/flask-api:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
